# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BasicCalculations
                                 A QGIS plugin
 This plugin calculates the surface area and the difference in height.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-30
        copyright            : (C) 2024 by Alicja Adamów-Bielkowicz, Artur Urban, Mateusz Trojanowski
        email                : alicja.adamow-bielkowicz.stud@pw.edu.pl, artur.urban.stud@pw.edu.pl, mateusz.trojanowski3.stud@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BasicCalculations class from file BasicCalculations.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .proj_2 import BasicCalculations
    return BasicCalculations(iface)
