# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BasicCalculationsDialogBase(object):
    def setupUi(self, BasicCalculationsDialogBase):
        BasicCalculationsDialogBase.setObjectName("BasicCalculationsDialogBase")
        BasicCalculationsDialogBase.resize(506, 350)
        self.button_box = QtWidgets.QDialogButtonBox(BasicCalculationsDialogBase)
        self.button_box.setGeometry(QtCore.QRect(130, 290, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.mMapLayerComboBox = QgsMapLayerComboBox(BasicCalculationsDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(130, 90, 241, 41))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label = QtWidgets.QLabel(BasicCalculationsDialogBase)
        self.label.setGeometry(QtCore.QRect(130, 50, 161, 31))
        self.label.setObjectName("label")

        self.retranslateUi(BasicCalculationsDialogBase)
        self.button_box.accepted.connect(BasicCalculationsDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(BasicCalculationsDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BasicCalculationsDialogBase)

    def retranslateUi(self, BasicCalculationsDialogBase):
        _translate = QtCore.QCoreApplication.translate
        BasicCalculationsDialogBase.setWindowTitle(_translate("BasicCalculationsDialogBase", "Basic Calculations"))
        self.label.setText(_translate("BasicCalculationsDialogBase", "Choose layer:"))
from qgsmaplayercombobox import QgsMapLayerComboBox
